### ISSUE TITLE
[needs review] Redudant modulo

### ISSUE THREAD

**Issue by Zdendaki** [JachyHm/MapyCZforTS2#1]
These lines of code have probably redudant modulo operation.
https://github.com/JachyHm/MapyCZforTS2/blob/fa35e7cd6ab31a9db537456e4a2e9025fb3c4b4d/MapTile.cs#L197
https://github.com/JachyHm/MapyCZforTS2/blob/fa35e7cd6ab31a9db537456e4a2e9025fb3c4b4d/MapTile.cs#L207

**Comment by Zdendaki** [comment]
sracz

**Comment by JachyHm** [comment]
Won't fix atm, time cost too high.

**Comment by Zdendaki** [comment]
ultrasracz
