### ISSUE TITLE
We do not have a map basis for this approach. Try choosing a different zoom or a different map background.

### ISSUE THREAD

**Issue by DanThe12** [JachyHm/MapyCZforTS2#2]
Hi, this error bothers me a lot. Every time I want to use the overlay, I get this error, even if I have set the correct zoom. is there any way to solve the problem?
![image](https://github.com/JachyHm/MapyCZforTS2/assets/94494137/ecf146d5-ccf5-44ff-939a-51a137d9a1fe)

**Comment by JachyHm** [comment]
Hi,
this error unfortunately means, that there is no data available for this zoom and mapset combination.
If this error appears on the most basic mapset (Bing ortophoto), you have to lower the zoom slider in game settings until somethign appears.
Although Bing aerial mapset is worldwide, in some countries, they have only lower resolution photos.
